### ISSUE TITLE
The "Overview Dashboard" terraform code isn't static

### ISSUE THREAD

**Issue by lswith** [SumoLogic-Labs/slogen#44]
The "tf/dashboards/overview-<service>.tf" file is constantly changing, each time I run "slogen . --apply --clean".

I believe this is because the map is unordered and the rows are being pulled out arbitrarily: https://github.com/SumoLogic-Labs/slogen/blob/main/libs/overview.go#L193

This means that my terraform code changes on each run, rather than being [hermetic](https://docs.bazel.build/versions/main/hermeticity.html). 

This is a low priority, but it would be nice to have these rows sorted.

**Comment by agaurav** [comment]
Agreed, all the need loops in templates should be sorted by the resource name.
should be an easy change.

**Comment by agaurav** [comment]
fixed in https://github.com/SumoLogic-Labs/slogen/pull/51/commits/9cc3f5932c277d26bbd5a5236263d4a638c2049d
